version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    depends_on:
      - frontend
